### ISSUE TITLE
addUser command able to add users with the same name and password

### ISSUE THREAD

**Issue by yao-feng** [CS2103-AY1819S1-W10-3/main#190]
This will create problems for user login because with the same name and password, Event Organiser will not be able to differentiate these two user accounts.

**Comment by adjscent** [comment]
Test commands:
addUser n/James Ho p/22224442 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague pass/password
addUser n/James Ho p/22224444 e/notjamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague pass/password
